spring:
  profiles.active: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: local
  redis:
    redisHostName: localhost
    redisPort: 6379

---
spring:
  profiles: cloud
  application:
    name: ${vcap.application.application_name:ccm-ui}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}